// Code generated by goctl. DO NOT EDIT.
package types

type RecommendReq struct {
}

type RecommendResply struct {
	Code    int64          `json:"Code"`
	Message string         `json:"Message"`
	Data    []*ProductItem `json:"Data"`
}

type ProductListReq struct {
	Page        int64  `json:"page"`
	PageSize    int64  `json:"pageSize"`
	ProductName string `json:"productName"`
}

type ProductListResply struct {
	Code       int64                     `json:"Code"`
	Message    string                    `json:"Message"`
	Page       int64                     `json:"Page"`
	PageSize   int64                     `json:"PageSize"`
	TotalCount int64                     `json:"TotalCount"`
	Data       map[int]map[string]string `json:"Data"`
}

type ProductItem struct {
	ID          int64   `json:"id"`
	Title       string  `json:"title"`
	CoverPic    string  `json:"coverPic"`
	Property    string  `json:"property"`
	MtPrice     float64 `json:"mtPrice"`
	DisPrice    float64 `json:"disPrice"`
	Stock       int64   `json:"stock"`
	State       int64   `json:"state"`
	SalesVolume int64   `json:"salesVolume"`
	Images      string  `json:"images"`
	Detail      string  `json:"detail"`
	CreateTime  string  `json:"createTime"`
	UpdateTime  string  `json:"updateTime"`
}

type ProductDetailReq struct {
	PorductId int64 `json:"porductId"`
}

type CateListReq struct {
	Pid int64 `json:"pid"`
}

type CommonResply struct {
	Code    int64                     `json:"Code"`
	Message string                    `json:"Message"`
	Data    map[int]map[string]string `json:"Data"`
}
